config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :maintenance_items do
    resources :maintenance_logs, only: [:index, :show, :new, :edit, :create]
    resources :maintenance_categories, only: [:index, :show, :new, :edit, :create]
  end 
  resources :maintenance_logs
  resources :maintenance_categories 

  get 'past_due', to: "maintenance_logs#past_due"
  get 'upcoming', to: "maintenance_logs#upcoming"

  get 'maintenance_logs/:id/log_data', to: 'maintenance_logs#log_data'
  
  root "maintenance_items#index"

end

app/models/maintenance_log.rb
class MaintenanceLog < ActiveRecord::Base
  belongs_to :maintenance_item
  belongs_to :maintenance_category
  validates :maintenance_category, presence: true
  validates :cost, numericality: true
  validate :starts_after_today?, :due_before_start?

  def maintenance_category_attributes=(category_attributes)
    #ensures that radio button only used if the fill in the name spot is empty
    if category_attributes[:name].empty?
      category = MaintenanceCategory.find_by(id: category_attributes[:id])
    else
      category = MaintenanceCategory.find_or_create_by(name: category_attributes[:name])
    end
    self.maintenance_category = category 
  end

  def starts_after_today?
    if date_performed.present? && date_performed > Date.today
      errors.add(:date_performed, "can't be in the future")
    end
  end

  def due_before_start?
    if date_due.present? && date_due < date_performed
      errors.add(:date_due, "can't be before the performed date")
    end
  end

  def category_blank?(att)
    att['name'].blank?
  end

  def self.past_due
    #returns list of all logs that are past due
    where("date_due <=?", Time.current)
  end

  def self.upcoming
    #returns list of all logs that'll be due in the next month
    where("date_due <=?", Time.current + 30.days)
  end

  # def self.current_user_logs
  #   @current_logs=[]
  #   @items = current_user.maintenance_items
  #   @items.each do |item|
  #     item.maintenance_logs.each do |log|
  #      @current_logs << log
  #     end
  #   end
  # end

end

app/controllers/maintenance_logs_controller.rb
class MaintenanceLogsController < ApplicationController

  def past_due
    @current_user_maintenance_logs = []
    @maintenance_items = current_user.maintenance_items
    @maintenance_items.each do |item|
      item.maintenance_logs.past_due.each do |log|
        @current_user_maintenance_logs << log
      end
    end
  end

  def upcoming
    @current_user_maintenance_logs = []
    @maintenance_items = current_user.maintenance_items
    @maintenance_items.each do |item|
      item.maintenance_logs.upcoming.each do |log|
        @current_user_maintenance_logs << log
      end
    end
  end

  def index
    if params[:maintenance_category_id]
      @maintenance_category = MaintenanceCategory.find_by(id: params[:maintenance_category_id])
      if @maintenance_category.nil?
        redirect_to maintenance_category_path, alert: "That category doesn't exist"
      else
        @maintenance_logs = @maintenance_category.maintenance_logs
      end
    else 
      @maintenance_logs = MaintenanceLog.all
    end
  end

  def new
    if params[:maintenance_item_id] && !MaintenanceItem.exists?(params[:maintenance_item_id])
      redirect_to root_path, alert: "that item doesn't exist"
    else 
      @maintenance_item = MaintenanceItem.find(params[:maintenance_item_id])
      @maintenance_log = @maintenance_item.maintenance_logs.build
    end
  end

  def create
    if params[:maintenance_item_id] && !MaintenanceItem.exists?(params[:maintenance_item_id])
      redirect_to maintenance_item_path, alert: "that item doesn't exist"
    else 
      @maintenance_item = MaintenanceItem.find(params[:maintenance_item_id]) 
      #@maintenance_item = MaintenanceItem.find(params[:maintenance_log][:maintenance_category_attributes][:id])
      @maintenance_log = @maintenance_item.maintenance_logs.create(maintenance_log_params)
      if @maintenance_log.valid?
        respond_to do |format|
          format.html {redirect_to maintenance_item_maintenance_log_path(@maintenance_item, @maintenance_log)}
          format.json { render json: @maintenance_log}
        end
      else
        render :new
      end
    end
  end

  def update
    @maintenance_log = MaintenanceLog.find(params[:id])
    @maintenance_log.update(maintenance_log_params)
    if @maintenance_log.save
      redirect_to maintenance_log_path(@maintenance_log)
    else 
      render :edit
    end
  end

  def destroy
    MaintenanceLog.find(params[:id]).destroy
    redirect_to :root
  end

  def show
    if params[:maintenance_category_id]
      @maintenance_category = MaintenanceCategory.find_by(id: params[:maintenance_category_id])
      @maintenance_log = @maintenance_category.maintenance_logs.find_by(id: params[:id])
      if @maintenance_log.nil?
        redirect_to maintenance_category_maintenance_log_path(@maintenance_category), alert: "log not found"
      end 
    else
      @maintenance_log = MaintenanceLog.find(params[:id])
    end

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @maintenance_log}
    end
  end

  def edit 
    if params[:maintenance_category_id]
      maintenance_category = MaintenanceCategory.find_by(id: params[:maintenance_category_id])
      if maintenance_category.nil?
        redirect_to maintenance_category_path, alert: "category not found"
      else 
        @maintenance_log = maintenance_category.maintenance_logs.find_by(id: params[:id])
        redirect_to maintenance_category_maintenance_logs_path, alert: "log not found"
      end 
    else 
      @maintenance_log = MaintenanceLog.find(params[:id])
    end 
  end

  private

  def maintenance_log_params
    params.require(:maintenance_log).permit(:notes, :tools, :cost, :date_performed, :date_due, :maintenance_item_id, :maintenance_category_id, maintenance_category_attributes: [:name, :id] )
  end

end

app/helpers/maintenance_logs_helper.rb
module MaintenanceLogsHelper

  def formatted_date_performed(maintenance_log)
    maintenance_log.date_performed.strftime("%b %d, %Y")
  end

  def formatted_date_due(maintenance_log)
    maintenance_log.date_due.strftime("%b %d, %Y")
  end

  def time_entered?
    #returns true if date_performed/date_due exists
  end
end

app/views/maintenance_logs/_form.html.erb
<% if @maintenance_log.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@maintenance_log.errors.count, "error") %> prohibited this log from being saved:
    </h2>
    
    <ul>
      <% @maintenance_log.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@maintenance_item, @maintenance_log], :html => {:class => "form-group"} do |f| %>

  <div class="form-group col-auto">
    <p>Add or Select a Category</p>
    <%= f.fields_for :maintenance_category, @maintenance_log.build_maintenance_category do |category| %>
      <%= category.collection_radio_buttons :id, @maintenance_item.maintenance_categories, :id, :name %><br>
      <%= category.text_field :name, :class => 'form-control', :placeholder => "Add a New Category" %>
    <% end %>
  </div>

  <div class="form-group col-auto">
    <%= f.label :date_performed %>
    <%= f.date_select :date_performed, :class => 'form-control' %><br>
    <%= f.label :date_due, :class => '' %>
    <%= f.date_select :date_due, :class => 'form-control' %><br>
  </div>

  <div class="form-group col-auto">
    <%= f.label :tools %>
    <%= f.text_field :tools, :class => 'form-control', :placeholder => "Enter Tools" %>
  </div>

  <div class="form-group col-auto">  
  <%= f.label :cost %>
  <%= f.number_field :cost, :class => 'form-control', :placeholder => "Enter Cost" %>
  </div>

  <div class="form-group col-auto">  
  <%= f.label :notes %>
  <%= f.text_area :notes, :class => 'form-control', :placeholder => "Enter Any Notes" %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/maintenance_logs/edit.html.erb
<h3 class='col-auto'>Edit</h3>

<%= render 'form' %>

app/views/maintenance_logs/new.html.erb
<h3>Add a New Log for <%= @maintenance_log.maintenance_item.name %></h3>

<%= render 'form' %>
<%= link_to  "Back to Logs for #{@maintenance_log.maintenance_item.name}", maintenance_item_path(@maintenance_log.maintenance_item_id), html_options = {class: 'badge badge-primary'} %><br>

app/views/maintenance_logs/past_due.html.erb
<h3>Past Due</h3>

<% if @current_user_maintenance_logs.any? %>
  <%= @current_user_maintenance_logs.each do |log| %>
    <%= link_to  "#{log.maintenance_category.name} Was due on #{formatted_date_due(log)}", maintenance_log_path(log) %><br>
  <% end %>
<% else %>
  <p>You're an adequate mechanic, nothing is past due</p>
<% end %>

app/views/maintenance_logs/show.html.erb
<div class="form-group">
  <h3>Log for <%= @maintenance_log.maintenance_category.name %></h3>

  <div class="col-auto">
    <h5>Date Performed:</h5>
    <% if @maintenance_log.date_performed %>
      <%= formatted_date_performed(@maintenance_log) %><br>
    <% else %>
      No Date Entered
    <% end %>
  </div>
  <br>

  <div class="col-auto">
    <h5>Date due:</h5>
    <% if @maintenance_log.date_due %>
      <%= formatted_date_due(@maintenance_log) %><br>
    <% else %>
      No Date Entered
    <% end %>
  </div>
  <br>

  <div class="col-auto">
    <h5>Tools Required:</h5>
    <%= @maintenance_log.tools %><br>
  </div>
  <br>

  <div class="col-auto">
    <h5>Cost:</h5>
    $<%= @maintenance_log.cost %><br>
  </div>
  <br>

  <div class="col-auto">
    <h5>Notes:</h5>
    <%= @maintenance_log.notes %><br>
  </div>
  <br>
  
  <div class="col-auto">
    <%= link_to  "Back to Logs for #{@maintenance_log.maintenance_item.name}", maintenance_item_path(@maintenance_log.maintenance_item_id), html_options = {class: 'badge badge-primary'} %><br>
    <%= link_to  "Edit", edit_maintenance_item_maintenance_log_path(@maintenance_log.maintenance_item_id, @maintenance_log), html_options = {class: 'badge badge-primary'} %><br>
    <%= link_to  "Delete this log entry", @maintenance_log, method: :delete, data: { confirm: "You sure?"}, class: "badge badge-primary" %><br>
    <%= link_to  "Add a New Entry", new_maintenance_item_maintenance_log_path(@maintenance_log.maintenance_item_id), html_options = {class: 'badge badge-primary'} %><br>
  </div>
</div>

app/views/maintenance_logs/upcoming.html.erb
<h3>Upcoming Work</h3>

<% if @current_user_maintenance_logs.any? %>
  <%= @current_user_maintenance_logs.each do |log| %>
    <%= link_to  "#{log.maintenance_category.name} Will be due on #{formatted_date_due(log)}", maintenance_log_path(log) %><br>
  <% end %>
<% else %>
  <p>Enjoy the break, you don't have anything to do for the next month</p>
<% end %>