config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :maintenance_items do
    resources :maintenance_logs, only: [:index, :show, :new, :edit, :create]
    resources :maintenance_categories, only: [:index, :show, :new, :edit, :create]
  end 
  resources :maintenance_logs
  resources :maintenance_categories 

  get 'past_due', to: "maintenance_logs#past_due"
  get 'upcoming', to: "maintenance_logs#upcoming"

  get 'maintenance_logs/:id/log_data', to: 'maintenance_logs#log_data'
  
  root "maintenance_items#index"

end

app/models/maintenance_item.rb
class MaintenanceItem < ActiveRecord::Base
  belongs_to :user
  has_many :maintenance_categories, :through => :maintenance_logs
  has_many :maintenance_logs, :dependent => :destroy
  validates :name, presence: true
end

app/controllers/maintenance_items_controller.rb
class MaintenanceItemsController < ApplicationController
  before_action :set_maintenance_item, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      @maintenance_items = current_user.maintenance_items

      #For use with the 'show categories' button from the Maintenance Items Show page, copied below
      # <%= link_to  "Show Categories", maintenance_item_path(item), id: "categoryBtn_#{item.id}" ,class: 'btn align-self-center badge badge-primary' %>
      
      # @maintenance_item_ids = current_user.maintenance_item_ids
      # @cat_names = []
      # @logs = []
      # @maintenance_item_ids.each do |id|
      #   @logs << MaintenanceLog.find_by(maintenance_item_id: id)
      #   @logs.each do |log|
      #     @cat_names << MaintenanceCategory.find(log.maintenance_category_id).name
      #   end
      # end
 
    else 
      redirect_to new_user_session_path
    end

    respond_to do |format|
      format.html { render :index}
      format.json { render json: @maintenance_items}
    end
  end

  def new
    @maintenance_item = MaintenanceItem.new
  end

  def create
    @maintenance_item = current_user.maintenance_items.build(maintenance_item_params)
    if @maintenance_item.save
      redirect_to maintenance_item_path(@maintenance_item)
    else
      render :new
      # @maintenance_items = MaintenanceItem.all
      # redirect_to new_maintenance_item_path, alert: "Please enter a valid maintenance item"
    end
  end

  def update
    @maintenance_item.update(maintenance_item_params)
    redirect_to maintenance_item_path(@maintenance_item)
  end

  def destroy
    @maintenance_item.destroy
    redirect_to maintenance_items_path
  end

  def show
     # For use with form to make new log
    @maintenance_log = @maintenance_item.maintenance_logs.build
    render 
  end

  def edit 
  end

  private

  def set_maintenance_item
    @maintenance_item = MaintenanceItem.find(params[:id])
  end

  def maintenance_item_params
    params.require(:maintenance_item).permit(:name, :user_id)
  end

end

app/helpers/maintenance_items_helper.rb
module MaintenanceItemsHelper
end

app/views/maintenance_items/_form.html.erb
<% if @maintenance_item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@maintenance_item.errors.count, "error") %> prohibited this item from being saved:
    </h2>

    <ul>
      <% @maintenance_item.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @maintenance_item, :html => {:class => "form-group"} do |f| %>
  
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Enter New Maintenance Item Name" %><br>

  <%= f.submit class:'btn btn-primary' %>
<% end %>

app/views/maintenance_items/edit.html.erb
<h3>Edit <%= @maintenance_item.name %></h3>

<%= render 'form' %>

app/views/maintenance_items/index.html.erb
<h3>Maintenance Items</h3>
<div class="list-group">
  <% @maintenance_items.each do |item| %>
    <li class="d-flex align-items-start flex-md-row">
      <span class="badge badge-primary badge-pill">
        <%= item.maintenance_logs.past_due.count %>
      </span>
      <%= link_to item.name, maintenance_item_path(item), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

      <%= link_to  "Delete this item", item, method: :delete, data: { confirm: 'Are you sure about that?'}, class: 'btn align-self-center badge badge-primary' %>
    </li>
    
    <br>
    <div class="accordion">
      <div id="<%= "showCategory_#{item.id}" %>"></div>
    </div>
  <% end %>
</div>
<br>
<%= link_to 'Add New Maintenance Item', new_maintenance_item_path, html_options = {class: 'badge badge-primary'} %>

app/views/maintenance_items/new.html.erb
<h3>Add a New Maintenance Item</h3>

<%= render 'form' %>

<%= link_to 'Back', maintenance_items_path, html_options = {class: 'badge badge-primary'} %><br>

app/views/maintenance_items/show.html.erb
<h3>Maintenance Categories for <%= @maintenance_item.name %> </h3> 

<%= link_to  "Edit #{@maintenance_item.name}", edit_maintenance_item_path(@maintenance_item), html_options = {class: 'badge badge-dark'} %><br>
<br>

<div class="list-group">
  <% @maintenance_item.maintenance_categories.uniq.each do |category| %>
    <li class="d-flex align-items-start flex-md-row">
      <span class="badge badge-primary badge-pill">
        <%= category.maintenance_logs.past_due.count %>
      </span>
      <%= link_to  category.name, maintenance_item_maintenance_category_path(@maintenance_item, category), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

      <%= link_to  "Show Logs", maintenance_item_maintenance_category_path(@maintenance_item, category), id: "logBtn_#{category.id}" ,class: 'btn align-self-center badge badge-primary' %>
    </li>
    <br>
    <div class="accordion" >
      <div id="<%= "showLog_#{category.id}" %>"></div>
    </div>
  <% end %>
</div>
<br>

<div>
  <%= render 'maintenance_logs/form'%>
</div>

<div id="logResult">
  <p id="logDatePerformed"></p>
  <p id="logDateDue"></p>
  <p id="logCost"></p>
  <p id="logNotes"></p>
  <p id="logTools"></p>
</div>

<%= link_to  "Back To Maintenance Items", maintenance_items_path, html_options = {class: 'badge badge-primary'} %><br>
<%= link_to  "Add a New Maintenance Log", new_maintenance_item_maintenance_log_path(@maintenance_item), html_options = {class: 'badge badge-primary'} %><br>