config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :maintenance_items do
    resources :maintenance_logs, only: [:index, :show, :new, :edit, :create]
    resources :maintenance_categories, only: [:index, :show, :new, :edit, :create]
  end 
  resources :maintenance_logs
  resources :maintenance_categories 

  get 'past_due', to: "maintenance_logs#past_due"
  get 'upcoming', to: "maintenance_logs#upcoming"

  get 'maintenance_logs/:id/log_data', to: 'maintenance_logs#log_data'
  
  root "maintenance_items#index"

end

app/models/maintenance_category.rb
class MaintenanceCategory < ActiveRecord::Base
  has_many :maintenance_items, :through => :maintenance_logs
  has_many :maintenance_logs
  validates :name, presence: true
end

app/controllers/maintenance_categories_controller.rb
class MaintenanceCategoriesController < ApplicationController
  # before_action :set_maintenance_category, only: [:show, :edit, :update, :destroy]

  def index
    if params[:maintenance_item_id]
      @maintenance_item = MaintenanceItem.find_by(id: params[:maintenance_item_id])
      if @maintenance_item.nil?
        redirect_to maintenance_item_path, alert: "That Maintenance Item Does Not Exist"
      else
        @maintenance_categories = @maintenance_item.maintenance_categories
      end
    else 
      @maintenance_categories = MaintenanceCategory.all
    end

  end

  def new
    if params[:maintenance_item_id] && !MaintenanceItem.exists?(params[:maintenance_item_id])
      redirect_to maintenance_item_path, alert: "Maintenance Item not found"
    else
      @maintenance_item = MaintenanceItem.find(params[:maintenance_item_id])
      @maintenance_category = @maintenance_item.maintenance_categories.build
    end
  end

  def create
    ## You also need to check if belongs to the right user 
    if params[:maintenance_item_id] && !MaintenanceItem.exists?(params[:maintenance_item_id])
      redirect_to maintenance_item_path, alert: "Maintenance Item not found"
    else
      @maintenance_item = MaintenanceItem.find(params[:maintenance_item_id])
      if @maintenance_category = @maintenance_item.maintenance_categories.create(maintenance_category_params)
        redirect_to maintenance_item_maintenance_category_path(@maintenance_item, @maintenance_category)
      else 
        render :new
      end
    end 

  end

  def update
    @maintenance_category = MaintenanceCategory.find(params[:id])
    @maintenance_category.update

    if @maintenance_category.save
      redirect_to maintenance_category_path(@maintenance_category)
    else
      render :edit
    end
  end

  def destroy
    MaintenanceCategory.find(params[:id]).destroy
    redirect_to :root
  end

  def show
    
    if params[:maintenance_item_id]
      @maintenance_item = MaintenanceItem.find_by(id: params[:maintenance_item_id])
      @maintenance_category = @maintenance_item.maintenance_categories.find_by(id: params[:id])
      @maintenance_logs = @maintenance_category.maintenance_logs
      if @maintenance_category.nil?
        redirect_to maintenance_item_maintenance_category_path(@maintenance_item), alert: "Category not found"
      end
    else 
      @maintenance_category = MaintenanceCategory.find(params[:id])
    end

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @maintenance_logs}
    end
    
  end

  def edit 
    if params[:maintenance_item_id]
      maintenance_item = MaintenanceItem.find_by(id: params[:maintenance_item_id])
      if maintenance_item.nil?
        redirect_to maintenance_item_path, alert: "Item not found"
      else 
        @maintenance_category = maintenance_item.maintenance_categories.find_by(id: params[:id])
        redirect_to maintenance_item_maintenance_categories_path, alert: "Category not found" 
      end
    else
      @maintenance_category = MaintenanceCategory.find(params[:id])
    end
  end

  private

  # def set_maintenance_category
  #   @maintenance_category = MaintenanceCategory.find(params[:id])
  # end

  def maintenance_category_params
    params.require(:maintenance_category).permit(:name, :maintenance_item_id) 
  end
end

app/helpers/maintenance_categories_helper.rb
module MaintenanceCategoriesHelper
end

app/views/maintenance_categories/_form.html.erb
<% if @maintenance_category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@maintenance_category.errors.count, "error") %> prohibited this category from being saved:
    </h2>

    <ul>
      <% @maintenance_category.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>
<%= form_for [@maintenance_item, @maintenance_category], :html => {:class => "form-group"} do |f| %>
  
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Enter New Category Name" %><br>

  <%= f.submit class: 'btn btn-primary' %><br>

<% end %>

app/views/maintenance_categories/edit.html.erb
<h3>Edit <%= @maintenance_category.name %></h3>

<%= render 'form' %>

app/views/maintenance_categories/new.html.erb
<h3>Make a New Category</h3>

<%= render 'form' %>
<br>
<%= link_to  "Back to Maintenance Categories", maintenance_item_path(@maintenance_item), html_options = {class: 'badge badge-primary'} %><br>

app/views/maintenance_categories/show.html.erb
<h3>Logs for <%= @maintenance_category.name %></h3>

<%= link_to  "Edit #{@maintenance_category.name}", edit_maintenance_category_path(@maintenance_category), html_options = {class: 'badge badge-dark'} %><br>
<br>

<div <li class="list-group"> 
  <%= @maintenance_category.maintenance_logs.each do |log| %>
    <% unless log.date_performed.nil? %>
      <li class="d-flex align-items-start flex-md-row">
        <%= link_to  "Performed on #{formatted_date_performed(log)}" , maintenance_log_path(log), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

        <%= link_to  "Show Details", maintenance_log_path(log), id: "detailsBtn_#{log.id}" ,class: 'btn align-self-center badge badge-primary' %>
      </li>
      <br>
      <div class="accordion" >
        <div id="<%= "showDetails_#{log.id}" %>"></div>
      </div>
    <% end %>
  <% end %>
</div>
<br>

<%= link_to "Back to #{@maintenance_item.name}", maintenance_item_path(@maintenance_item), html_options = {class: 'badge badge-primary'} %><br>
<%= link_to  "Add a new log entry", new_maintenance_item_maintenance_log_path(@maintenance_item), html_options = {class: 'badge badge-primary'} %>