config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :maintenance_items do
    resources :maintenance_logs, only: [:index, :show, :new, :edit, :create]
    resources :maintenance_categories, only: [:index, :show, :new, :edit, :create]
  end 
  resources :maintenance_logs
  resources :maintenance_categories 

  get 'past_due', to: "maintenance_logs#past_due"
  get 'upcoming', to: "maintenance_logs#upcoming"

  get 'maintenance_logs/:id/log_data', to: 'maintenance_logs#log_data'
  
  root "maintenance_items#index"

end

app/views/layouts/_category_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
  <% if user_signed_in? %>
    <div class="d-flex">
      <a class="navbar-brand">MT</a>
    </div>
    <button class="navbar-toggler order-3" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-between" id="collapsingNavbar">
      <div><!--placeholder to evenly space flexbox items and center links--></div>
      <ul class="navbar-nav">
        <li class="nav_item nav-link">
          <a href="/">Home</a>
        </li>
        <li class="nav_item nav-link">
          <a href="/upcoming">Upcoming</a>
        </li>
        <li class="nav_item nav-link">
          <a href="/past_due">Past Due</a>
        </li>
        <li class="nav_item nav-link">
          <%= link_to  "Categories", maintenance_item_maintenance_categories_path( ) %>
        </li>
        <li class="nav_item nav-link">
          <%= link_to  "Log Out", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
      <ul class="nav navbar-nav flex-row">
        <li class="nav_item nav-link">Welcome,
          <%= current_user.email %>
        </li>
      </ul>
    </div>
  <% else %>
    <a class="navbar-brand mx-auto" href="/users/sign_in">Sign in</a>
  <% end %>

</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
  <% if user_signed_in? %>
    <div class="d-flex">
      <a class="navbar-brand">MT</a>
    </div>
    <button class="navbar-toggler order-3" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-between" id="collapsingNavbar">
      <div><!--placeholder to evenly space flexbox items and center links--></div>
      <ul class="navbar-nav">
        <li class="nav_item nav-link">
          <a href="/">Home</a>
        </li>
        <li class="nav_item nav-link">
          <a href="/upcoming">Upcoming</a>
        </li>
        <li class="nav_item nav-link">
          <a href="/past_due">Past Due</a>
        </li>
        <li class="nav_item nav-link">
          <%= link_to  "Log Out", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
      <ul class="nav navbar-nav flex-row">
        <li class="nav_item nav-link">Welcome,
          <%= current_user.email %>
        </li>
      </ul>
    </div>
  <% else %>
    <a class="navbar-brand mx-auto" href="/users/sign_in">Sign in</a>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MaintenanceTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="mx-auto col-sm-6">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</div>

</body>
</html>